package model.pojo;
// Generated Oct 14, 2012 3:19:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private int documentId;
     private String url;
     private Integer totalPosts;
     private String hash;
     private String title;
     private Set postses = new HashSet(0);

    public Document() {
    }

	
    public Document(int documentId) {
        this.documentId = documentId;
    }
    public Document(int documentId, String url, Integer totalPosts, String hash, String title, Set postses) {
       this.documentId = documentId;
       this.url = url;
       this.totalPosts = totalPosts;
       this.hash = hash;
       this.title = title;
       this.postses = postses;
    }
   
    public int getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(int documentId) {
        this.documentId = documentId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getTotalPosts() {
        return this.totalPosts;
    }
    
    public void setTotalPosts(Integer totalPosts) {
        this.totalPosts = totalPosts;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }




}


