package model.pojo;
// Generated Oct 14, 2012 3:19:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private int tagId;
     private String tagName;
     private Set tagsForPosts = new HashSet(0);

    public Tag() {
    }

	
    public Tag(int tagId) {
        this.tagId = tagId;
    }
    public Tag(int tagId, String tagName, Set tagsForPosts) {
       this.tagId = tagId;
       this.tagName = tagName;
       this.tagsForPosts = tagsForPosts;
    }
   
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }
    public Set getTagsForPosts() {
        return this.tagsForPosts;
    }
    
    public void setTagsForPosts(Set tagsForPosts) {
        this.tagsForPosts = tagsForPosts;
    }




}


