package model.pojo;
// Generated Oct 15, 2012 8:53:44 PM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;
import java.util.Date;

/**
 * TagCollect generated by hbm2java
 */
public class TagCollect  implements java.io.Serializable {


     private int id;
     private String tagName;
     private Timestamp dateTagged;

    public TagCollect() {
    }
    
    public TagCollect(int id, String tagName) {
        this.id = id;
        this.tagName = tagName;
    }
    public TagCollect(int id, String tagName, Timestamp dateTagged) {
       this.id = id;
       this.tagName = tagName;
       this.dateTagged = dateTagged;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }
    public Date getDateTagged() {
        return this.dateTagged;
    }
    
    public void setDateTagged(Timestamp dateTagged) {
        this.dateTagged = dateTagged;
    }




}


