package model.pojo;
// Generated Oct 14, 2012 3:19:08 PM by Hibernate Tools 3.2.1.GA



/**
 * TagsForPost generated by hbm2java
 */
public class TagsForPost  implements java.io.Serializable {


     private TagsForPostId id;
     private Tag tag;
     private Posts posts;
     private Integer postTagId;

    public TagsForPost() {
    }

	
    public TagsForPost(TagsForPostId id, Tag tag, Posts posts) {
        this.id = id;
        this.tag = tag;
        this.posts = posts;
    }
    public TagsForPost(TagsForPostId id, Tag tag, Posts posts, Integer postTagId) {
       this.id = id;
       this.tag = tag;
       this.posts = posts;
       this.postTagId = postTagId;
    }
   
    public TagsForPostId getId() {
        return this.id;
    }
    
    public void setId(TagsForPostId id) {
        this.id = id;
    }
    public Tag getTag() {
        return this.tag;
    }
    
    public void setTag(Tag tag) {
        this.tag = tag;
    }
    public Posts getPosts() {
        return this.posts;
    }
    
    public void setPosts(Posts posts) {
        this.posts = posts;
    }
    public Integer getPostTagId() {
        return this.postTagId;
    }
    
    public void setPostTagId(Integer postTagId) {
        this.postTagId = postTagId;
    }




}


