package model.pojo;
// Generated Oct 14, 2012 3:19:08 PM by Hibernate Tools 3.2.1.GA



/**
 * TagsForPostId generated by hbm2java
 */
public class TagsForPostId  implements java.io.Serializable {


     private int tagId;
     private int postId;

    public TagsForPostId() {
    }

    public TagsForPostId(int tagId, int postId) {
       this.tagId = tagId;
       this.postId = postId;
    }
   
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }
    public int getPostId() {
        return this.postId;
    }
    
    public void setPostId(int postId) {
        this.postId = postId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TagsForPostId) ) return false;
		 TagsForPostId castOther = ( TagsForPostId ) other; 
         
		 return (this.getTagId()==castOther.getTagId())
 && (this.getPostId()==castOther.getPostId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTagId();
         result = 37 * result + this.getPostId();
         return result;
   }   


}


